version: "3"

networks: 
  net-api:
    driver: bridge
  net-broker:
    driver: bridge
  net-banco:
    driver: bridge

services:

  wrk-api:
    hostname: wrk-api
    container_name: wrk-api
    build: api
    restart: always
    # ports:
    #   - "3000:80"
    depends_on:
      - "wrk-redis"
      - "wrk-rabbitmq"
    links:
      - "wrk-redis"
      - "wrk-rabbitmq"
    networks:
      - net-api
      - net-banco
      - net-broker

  # wrk-api-02:
  #   hostname: wrk-api-02
  #   container_name: wrk-api-02
  #   build: api
  #   restart: always
  #   # ports:
  #   #   - "3001:80"
  #   depends_on:
  #     - "wrk-redis"
  #     - "wrk-rabbitmq"
  #   links:
  #     - "wrk-redis"
  #     - "wrk-rabbitmq"
  #   networks:
  #     - net-api
  #     - net-banco
  #     - net-broker

  # wrk-api-03:
  #   hostname: wrk-api-03
  #   container_name: wrk-api-03
  #   build: api
  #   restart: always
  #   # ports:
  #   #   - "3002:80"
  #   depends_on:
  #     - "wrk-redis"
  #     - "wrk-rabbitmq"
  #   links:
  #     - "wrk-redis"
  #     - "wrk-rabbitmq"
  #   networks:
  #     - net-api
  #     - net-banco
  #     - net-broker

  wrk-consumer:
    container_name: wrk-consumer
    build: "worker-consumer"
    restart: always
    depends_on:
      - "wrk-redis"
      - "wrk-rabbitmq"
    links:
      - "wrk-redis"
      - "wrk-rabbitmq"
    networks:
      - net-api
      - net-banco
      - net-broker

  wrk-nginx:
    container_name: wrk-nginx
    build: nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    depends_on:
      - "wrk-api"
    links:
      - "wrk-api"
    networks:
      - net-api
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wrk-rabbitmq:
    container_name: wrk-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: always
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "15672" ]
      interval: 3s
      timeout: 10s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='sdfgdsgdfgdfg'
      - CLUSTERED=true
    networks:
      - net-broker
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    labels:
      NAME: "rabbitmq1"

  wrk-redis:
    container_name: wrk-redis
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass 123 --appendonly yes
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis/data/:/data
    networks:
      - net-banco

  # wrk-redis-commander:
  #   container_name: redis-ui
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:localhost:6379
  #     - REDIS_PASSWORD=123
  #     - HTTP_USER=admin
  #     - HTTP_PASSWORD=admin
  #   ports:
  #     - 8082:8081
  #   depends_on:
  #     - "worker-redis"
  #   networks:
  #     - net-banco

  # wrk-mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_DATABASE: admin
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   networks:
  #     - net-banco
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodb/data:/data/db

  # wrk-mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #   networks:
  #     - net-banco
    # depends_on:
    #   - "worker-mongo"

  wrk-jaeger:
    container_name: wrk-jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_AGENT_HOST=jaeger
      - LOG_LEVEL=debug
    labels:
        NAME: "jaeger-agent"
    restart: on-failure
    networks:
      - net-api
      - net-broker
