---
apiVersion: batch/v1 # batch/v1beta1
kind: CronJob
metadata:
  name: wrk-alrt-adm-ativos
  namespace: default
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: wrk-alrt-adm-ativos
              image: chrismarsilva/cms-tnb-alrt-adm-ativos:latest
              envFrom:
                - configMapRef:
                    name: tnb-env-config
---