# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wrk-rabbit
#   namespace: default
# spec:
#   ports:
#     - name: ui
#       protocol: TCP
#       port: 15672
#       targetPort: 15672
#       nodePort: 31112 # 31112
#     - name: service
#       port: 5672
#       targetPort: 5672
#       protocol: TCP
#       nodePort: 31111 # 31111
#   selector:
#     app: wrk-rabbit
#   type: NodePort
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wrk-rabbit
#   namespace: default
#   labels:
#     app: wrk-rabbit
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wrk-rabbit
#   template:
#     metadata:
#       labels:
#         app: wrk-rabbit
#     spec:
#       containers:
#         - name: wrk-rabbit
#           image: rabbitmq:3-management
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 15671
#             - containerPort: 5671
#           volumeMounts:
#             - name: rabbitmqapp-home
#               mountPath: /var/rabbitmqapp_home
#       volumes:
#         - name: rabbitmqapp-home
#           emptyDir: {}
# ---